#ifndef MAINBOARD_ENGINE_EVENT_MESSAGE_TYPE_H
#define MAINBOARD_ENGINE_EVENT_MESSAGE_TYPE_H

#define ME_NO_EVENT_MESSAGE 0
#define ME_QUIT_MESSAGE 1
#define ME_CANNOT_GET_EVENT_MESSAGE -1

#endif //MAINBOARD_ENGINE_EVENT_MESSAGE_TYPE_H